apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-ai-agents
  title: AI Agents
  description: Frontend of the AI Agents plugin.
  annotations:
    github.com/project-slug: acarmisc/backstage-plugin-ai-agents
  tags:
    - backstage-plugin
    - ai
  links:
    - url: https://www.npmjs.com/package/@acarmisc/backstage-plugin-ai-agents
      title: npm
spec:
  type: backstage-frontend-plugin
  lifecycle: experimental
  owner: user:acarmisc
  system: backstage-plugin-ai-agents
